version: '3'

services:

  annotate:
    container_name: annotate-container
    image: leos_src
    network_mode: host
    build:
      context: .
    ports:
      - "9099:9099"
    volumes:
      - leos-volume:/src/
      - leos-script:/script/
    entrypoint: /script/fg-run-annotate.sh

  user-repository:
    container_name: user-repository-container
    image: leos_src
    network_mode: host
    ports:
      - "9095:9095"
    depends_on:
      - annotate
    volumes:
      - leos-volume:/src/
      - leos-script:/script/
    entrypoint: /script/fg-run-user-repository.sh

  repository:
    container_name: repository-container
    image: leos_src
    network_mode: host
    ports:
      - "9090:9090"
    depends_on:
      - user-repository
    volumes:
      - leos-volume:/src/
      - leos-script:/script/
    entrypoint: /script/fg-run-repository.sh

  leos:
    container_name: leos-container
    image: leos_src
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - repository
    volumes:
      - leos-volume:/src/
      - leos-script:/script/
    entrypoint: /script/fg-run-leos.sh

  akn4euutil:
    container_name: akn4euutil-container
    image: leos_src
    network_mode: host
    ports:
      - "9096:9096"
    depends_on:
      - leos
    volumes:
      - leos-volume:/src/
      - leos-script:/script/
    entrypoint: /script/fg-run-akn4euutil.sh

volumes:
  leos-volume:
  leos-script: